### PR TITLE
Add MoonTool version for Delphi and Lazarus

### PR DESCRIPTION
**Pull request by wp-xyz**
Added an updated version of the MoonTool demo which works for Delphi and Lazarus, including translations and chm help file. I removed support for Delphi 1. Because of this change and because of the replacement of the old translation code by gnugettext now, I put everything into a new folder NewMoonTool.

### CODE REVIEW

**Comment by wp-xyz** [comment]
Now I included your so far unsed eclipses form in the new MoonTool demo. I also fixed a memory leak of the TMoon component.

**Comment by wp-xyz** [comment]
Replaced the palette icon by png files for Lazarus suitable for LCL scaling

**Comment by wp-xyz** [comment]
Thanks for merging.

I'd like to publish a Lazarus-only version for the Lazarus Online-Package-Manager. My plan is to remove for it all the Delphi packages, the old DEMO folder, and the Delphi-related demo and test project files, plus maybe some more unused files.

This version will not be on github, it will only be a zipped snapshot which I would update from time to time if any further changes would occur in your original repository. 

Would this be ok for you? You mentioned in the readme that you want all source files to be distributed - and I would violate this requirement. 

Werner

**Comment by Ahoerstemeier** [comment]
Thanks for the contributions and re-awakening this project. As you noticed by the long inactivity, I no longer use Delphi, so I cannot check your merge requests and will simply accept your merges. As for the Online-Package-Distribution: I am fine with the component being distributed that way, if the source code is still available at this site. When I wrote the license, there was nothing like that package system, and no public source control, so the idea behind that request was to let user have access to the source code.

**Comment by wp-xyz** [comment]
Thanks for merging. In the meantime I decided to submit the entire DelphiMoon package to Lazarus Online Package Manager, not a Lazarus-only variant. For your information: The Online Package Manger is an addon to the Lazarus IDE which allows easy installation of third-party sources into the IDE.

**Pull request merged**
